const fs = require('fs');
const path = require('path');
const mysql = require('mysql2');
const mysqlPromise = require('mysql2/promise');
const { createDbConfig, projectRoot } = require('./db_env');
const defaultOutputFile = path.join(projectRoot, 'database/seed_anime_data.sql');

function normalizeJsonValue(value) {
  if (value === null || value === undefined) {
    return null;
  }

  if (typeof value === 'string') {
    return value;
  }

  return JSON.stringify(value);
}

function escapeValue(columnName, value) {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  if (columnName === 'tags' || columnName === 'cast' || columnName === 'cast_aliases') {
    return mysql.escape(normalizeJsonValue(value));
  }

  return mysql.escape(value);
}

function buildInsertStatement(tableName, columns, row) {
  const escapedColumns = columns.map((column) => `\`${column}\``).join(', ');
  const escapedValues = columns.map((column) => escapeValue(column, row[column])).join(', ');

  return `INSERT INTO \`${tableName}\` (${escapedColumns}) VALUES (${escapedValues});`;
}

async function main() {
  const outputFile = process.argv[2]
    ? path.resolve(process.argv[2])
    : defaultOutputFile;

  const connection = await mysqlPromise.createConnection(createDbConfig());

  try {
    const [animeRows] = await connection.query(`
      SELECT
        id,
        title,
        original_title,
        coverUrl,
        status,
        score,
        progress,
        totalEpisodes,
        durationMinutes,
        notes,
        tags,
        summary,
        DATE_FORMAT(start_date, '%Y-%m-%d') AS start_date,
        DATE_FORMAT(end_date, '%Y-%m-%d') AS end_date,
        DATE_FORMAT(premiere_date, '%Y-%m-%d') AS premiere_date,
        cast,
        cast_aliases,
        isFinished,
        DATE_FORMAT(createdAt, '%Y-%m-%d %H:%i:%s') AS createdAt,
        DATE_FORMAT(updatedAt, '%Y-%m-%d %H:%i:%s') AS updatedAt
      FROM anime
      ORDER BY id ASC
    `);

    const [historyRows] = await connection.query(`
      SELECT
        id,
        animeId,
        animeTitle,
        episode,
        DATE_FORMAT(watchedAt, '%Y-%m-%d %H:%i:%s') AS watchedAt
      FROM watch_history
      ORDER BY watchedAt ASC, id ASC
    `);

    const animeColumns = [
      'id',
      'title',
      'original_title',
      'coverUrl',
      'status',
      'score',
      'progress',
      'totalEpisodes',
      'durationMinutes',
      'notes',
      'tags',
      'summary',
      'start_date',
      'end_date',
      'premiere_date',
      'cast',
      'cast_aliases',
      'isFinished',
      'createdAt',
      'updatedAt',
    ];

    const historyColumns = ['id', 'animeId', 'animeTitle', 'episode', 'watchedAt'];
    const nextAnimeId = animeRows.length > 0 ? Number(animeRows[animeRows.length - 1].id) + 1 : 1;
    const nextHistoryId = historyRows.length > 0 ? Number(historyRows[historyRows.length - 1].id) + 1 : 1;

    const lines = [
      '-- Auto-generated by scripts/maintenance/export_anime_seed.js',
      `-- Source database: ${process.env.MYSQL_DATABASE}`,
      `-- Generated at: ${new Date().toISOString()}`,
      '-- Shared data only: anime + watch_history',
      'SET NAMES utf8mb4;',
      'SET FOREIGN_KEY_CHECKS = 0;',
      'DELETE FROM `watch_history`;',
      'DELETE FROM `anime`;',
      '',
    ];

    for (const row of animeRows) {
      lines.push(buildInsertStatement('anime', animeColumns, row));
    }

    lines.push('');

    for (const row of historyRows) {
      lines.push(buildInsertStatement('watch_history', historyColumns, row));
    }

    lines.push('');
    lines.push(`ALTER TABLE \`anime\` AUTO_INCREMENT = ${nextAnimeId};`);
    lines.push(`ALTER TABLE \`watch_history\` AUTO_INCREMENT = ${nextHistoryId};`);
    lines.push('SET FOREIGN_KEY_CHECKS = 1;');
    lines.push('');

    fs.writeFileSync(outputFile, lines.join('\n'), 'utf8');

    console.log(
      `Exported ${animeRows.length} anime rows and ${historyRows.length} watch history rows to ${path.relative(projectRoot, outputFile)}`
    );
  } finally {
    await connection.end();
  }
}

main().catch((error) => {
  console.error(error.message || error);
  process.exit(1);
});